export const jsonArr = [
  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@Y Combinator,Y Combinator,Private,Accelerator,2005,"Paul Graham= Robert Morris= Trevor Blackwell= Jessica Livingston","San Francisco= CA= USA","Artificial Intelligence= Biotech= Climate Change= Consumer= Crypto/Blockchain= Developer Tools= Education= Energy= Enterprise= Fintech= Gaming= Hardware= Healthcare= Marketplaces= Media/Content= Real Estate= Robotics= Social Impact= Space= Travel/Transpor","Airbnb= Dropbox= Stripe= Reddit= Coinbase= Instacart= Twitch= Docker= DoorDash= GitLab= Mixpanel= Zapier= Weebly= PagerDuty= Segment= Stripe= Patreon= Ginkgo Bioworks= Flexport= Brex= OpenAI",https://www.crunchbase.com/organization/y-combinator,https://pitchbook.com/profiles/accelerator/57272-46,https://twitter.com/ycombinator,https://www.linkedin.com/company/y-combinator,https://www.facebook.com/ycombinator,https://www.instagram.com/ycombinator/,https://www.youtube.com/user/ycombinator',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@NfX,NFX,Venture capital,"Finance= Technology",2015,"James Currier= Pete Flint= Gigi Levy-Weiss","San Francisco= California= United States","Consumer Internet= Marketplaces= Network Effects","DoorDash= Honeybook= Pendo= Placer.ai= PlayVS",https://www.crunchbase.com/organization/nfx,https://pitchbook.com/profiles/investor/180920-52,https://twitter.com/nfxguild,https://www.linkedin.com/company/nfx/,https://www.facebook.com/nfxguild/,https://www.instagram.com/nfx/,https://www.youtube.com/channel/UCULhmZWe-1ju2zKCHJXOy8g',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@AngelPad,AngelPad,Private,Startup accelerator,2010,Thomas Korte and Carine Magescas,"San Francisco= California= United States","Technology= internet= healthcare= mobile= and more","Postmates= Buffer= Munchery= Periscope= and many more",https://www.crunchbase.com/organization/angelpad,https://pitchbook.com/profiles/investor/10813-58#overview,https://twitter.com/angelpad,https://www.linkedin.com/company/angelpad/,https://www.facebook.com/AngelPadCo,https://www.instagram.com/angelpad/,https://www.youtube.com/user/AngelPadCo',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@XRC Labs,XRCLabs,Private,Retail technology,2018,"Pano Anthos= Kurt Collins= and Anthony Gustinis","New York= NY= United States","Retail technology= consumer goods= e-commerce= supply chain= omnichannel commerce","7 Chord= Birch Finance= Fashion Metric= Haste & Hustle= Lily= Memomi= Myagi= Perksy= Salesfloor= Shoppable= Smartzer= The Yes",https://www.crunchbase.com/organization/xrclabs,https://pitchbook.com/profiles/investor/234210-51,https://twitter.com/xrclabs,https://www.linkedin.com/company/xrclabs,https://www.facebook.com/xrclabs/,https://www.instagram.com/xrclabs/,https://www.youtube.com/channel/UCwM_Y68aLB1LJpvXOYvRsFg',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@Founderly,Founderly,Private,"Business Development= Entrepreneurship",2020,"Arpan Meka= Ashish Yelamanchili","New York= NY= United States",N/A,N/A,https://www.crunchbase.com/organization/founderly,https://pitchbook.com/profiles/company/499199-60,https://twitter.com/FounderlyHQ,https://www.linkedin.com/company/founderlyhq/,https://www.facebook.com/founderlyhq,https://www.instagram.com/founderlyhq/,N/A',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@Matter Chicago - Healthcare Incubator,Matter Health,Private,Healthcare Startup Accelerator,2014,Steven Collens,"Chicago= Illinois= United States","Healthcare= Medical Devices= HealthTech= Biotech","Explore Health= Careband= UnaliWear= Twistle",https://matter.health/microdata,https://pitchbook.com/profiles/investor/129957-28,https://twitter.com/matterhealth,https://www.linkedin.com/company/matter-health/,https://www.facebook.com/matterhealth,https://www.instagram.com/matterhealth/,https://www.youtube.com/channel/UCv1uV7B-Ko2Q-3x3zFJH52w',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@Gravity Ventures,Gravity Ventures,Venture Capital,Technology,2016,N/A,"San Francisco= California= United States",N/A,"Hone= Cala Health= Suki.AI= Lunit",https://www.crunchbase.com/organization/gravity-ventures,https://pitchbook.com/profiles/investor/154818-91,https://twitter.com/GravityVentures,https://www.linkedin.com/company/gravity-ventures/,N/A,https://www.instagram.com/gravity_ventures/,N/A',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@RealConnex,RealConnex,Private,Real Estate,2013,Roy Abrams,"New York= NY",Real estate,N/A,https://www.crunchbase.com/organization/realconnex,https://pitchbook.com/profiles/company/62355-08,https://twitter.com/realconnex,https://www.linkedin.com/company/realconnex/,https://www.facebook.com/RealConnex/,https://www.instagram.com/realconnex/,https://www.youtube.com/channel/UCbPMyzKGgDn9AKfQW5J8v5g',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@Tandem Capital,Tandem Capital,Venture Capital,Technology,2018,Sunil Nagaraj,"San Francisco= California= United States",N/A,"CryptoMove= Memority",https://www.crunchbase.com/organization/tandem-capital,https://pitchbook.com/profiles/investor/413571-50,https://twitter.com/TandemCapital,https://www.linkedin.com/company/tandem-capital,N/A,N/A,N/A',

  'title,g_name,g_type,g_industry,g_founded,g_founders,g_headquartersLocation,g_acceleratorProgramFocusAreas,g_notableAlumniCompanies,g_structuredDataUrl,g_pitchBookUrl,g_twitter,g_linkedIn,g_facebook,g_instagram,g_youTube@Ten50,Ten50,Private,Computer Software,2017,"David Greschler= Daniel Beveridge= Janelle Matthews","Seattle= Washington= United States","Kubernetes= cloud-native= DevOps= security",N/A,https://www.crunchbase.com/organization/ten50,https://pitchbook.com/profiles/company/253232-38,https://twitter.com/ten50hq,https://www.linkedin.com/company/ten50hq,https://www.facebook.com/ten50hq,https://www.instagram.com/ten50hq/,N/A',
];
